package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiAccessTokenPermissionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenPermissionAllPropertiesEquals(
        ApiAccessTokenPermission expected,
        ApiAccessTokenPermission actual
    ) {
        assertApiAccessTokenPermissionAutoGeneratedPropertiesEquals(expected, actual);
        assertApiAccessTokenPermissionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenPermissionAllUpdatablePropertiesEquals(
        ApiAccessTokenPermission expected,
        ApiAccessTokenPermission actual
    ) {
        assertApiAccessTokenPermissionUpdatableFieldsEquals(expected, actual);
        assertApiAccessTokenPermissionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenPermissionAutoGeneratedPropertiesEquals(
        ApiAccessTokenPermission expected,
        ApiAccessTokenPermission actual
    ) {
        assertThat(actual)
            .as("Verify ApiAccessTokenPermission auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenPermissionUpdatableFieldsEquals(
        ApiAccessTokenPermission expected,
        ApiAccessTokenPermission actual
    ) {
        assertThat(actual)
            .as("Verify ApiAccessTokenPermission relevant properties")
            .satisfies(a -> assertThat(a.getPermission()).as("check permission").isEqualTo(expected.getPermission()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenPermissionUpdatableRelationshipsEquals(
        ApiAccessTokenPermission expected,
        ApiAccessTokenPermission actual
    ) {
        assertThat(actual)
            .as("Verify ApiAccessTokenPermission relationships")
            .satisfies(a -> assertThat(a.getApiAccessToken()).as("check apiAccessToken").isEqualTo(expected.getApiAccessToken()));
    }
}
