package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiAccessTokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenAllPropertiesEquals(ApiAccessToken expected, ApiAccessToken actual) {
        assertApiAccessTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertApiAccessTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenAllUpdatablePropertiesEquals(ApiAccessToken expected, ApiAccessToken actual) {
        assertApiAccessTokenUpdatableFieldsEquals(expected, actual);
        assertApiAccessTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenAutoGeneratedPropertiesEquals(ApiAccessToken expected, ApiAccessToken actual) {
        assertThat(actual)
            .as("Verify ApiAccessToken auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenUpdatableFieldsEquals(ApiAccessToken expected, ApiAccessToken actual) {
        assertThat(actual)
            .as("Verify ApiAccessToken relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTokenPrefix()).as("check tokenPrefix").isEqualTo(expected.getTokenPrefix()))
            .satisfies(a -> assertThat(a.getTokenHash()).as("check tokenHash").isEqualTo(expected.getTokenHash()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getLastUsedAt()).as("check lastUsedAt").isEqualTo(expected.getLastUsedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getRevokedAt()).as("check revokedAt").isEqualTo(expected.getRevokedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiAccessTokenUpdatableRelationshipsEquals(ApiAccessToken expected, ApiAccessToken actual) {
        // empty method
    }
}
