package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiIngestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIngestionAllPropertiesEquals(ApiIngestion expected, ApiIngestion actual) {
        assertApiIngestionAutoGeneratedPropertiesEquals(expected, actual);
        assertApiIngestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIngestionAllUpdatablePropertiesEquals(ApiIngestion expected, ApiIngestion actual) {
        assertApiIngestionUpdatableFieldsEquals(expected, actual);
        assertApiIngestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIngestionAutoGeneratedPropertiesEquals(ApiIngestion expected, ApiIngestion actual) {
        assertThat(actual)
            .as("Verify ApiIngestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIngestionUpdatableFieldsEquals(ApiIngestion expected, ApiIngestion actual) {
        assertThat(actual)
            .as("Verify ApiIngestion relevant properties")
            .satisfies(a -> assertThat(a.getRequestId()).as("check requestId").isEqualTo(expected.getRequestId()))
            .satisfies(a -> assertThat(a.getIdempotencyKey()).as("check idempotencyKey").isEqualTo(expected.getIdempotencyKey()))
            .satisfies(a -> assertThat(a.getSourceSystem()).as("check sourceSystem").isEqualTo(expected.getSourceSystem()))
            .satisfies(a -> assertThat(a.getApiVersion()).as("check apiVersion").isEqualTo(expected.getApiVersion()))
            .satisfies(a -> assertThat(a.getEndpoint()).as("check endpoint").isEqualTo(expected.getEndpoint()))
            .satisfies(a -> assertThat(a.getClientReference()).as("check clientReference").isEqualTo(expected.getClientReference()))
            .satisfies(a -> assertThat(a.getReceivedAt()).as("check receivedAt").isEqualTo(expected.getReceivedAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getApiTokenIdSnapshot()).as("check apiTokenIdSnapshot").isEqualTo(expected.getApiTokenIdSnapshot())
            )
            .satisfies(a ->
                assertThat(a.getApiTokenPrefixSnapshot()).as("check apiTokenPrefixSnapshot").isEqualTo(expected.getApiTokenPrefixSnapshot())
            )
            .satisfies(a ->
                assertThat(a.getApiTokenNameSnapshot()).as("check apiTokenNameSnapshot").isEqualTo(expected.getApiTokenNameSnapshot())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIngestionUpdatableRelationshipsEquals(ApiIngestion expected, ApiIngestion actual) {
        assertThat(actual)
            .as("Verify ApiIngestion relationships")
            .satisfies(a ->
                assertThat(a.getTransactionIngestion()).as("check transactionIngestion").isEqualTo(expected.getTransactionIngestion())
            )
            .satisfies(a -> assertThat(a.getApiTokenIdSnapshot()).as("check apiTokenIdSnapshot").isEqualTo(expected.getApiTokenIdSnapshot())
            )
            .satisfies(a ->
                assertThat(a.getApiTokenPrefixSnapshot()).as("check apiTokenPrefixSnapshot").isEqualTo(expected.getApiTokenPrefixSnapshot())
            )
            .satisfies(a ->
                assertThat(a.getApiTokenNameSnapshot()).as("check apiTokenNameSnapshot").isEqualTo(expected.getApiTokenNameSnapshot())
            );
    }
}
