package com.fintrack.app.domain;

import static com.fintrack.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CreditAccountDetailsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreditAccountDetailsAllPropertiesEquals(CreditAccountDetails expected, CreditAccountDetails actual) {
        assertCreditAccountDetailsAutoGeneratedPropertiesEquals(expected, actual);
        assertCreditAccountDetailsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreditAccountDetailsAllUpdatablePropertiesEquals(CreditAccountDetails expected, CreditAccountDetails actual) {
        assertCreditAccountDetailsUpdatableFieldsEquals(expected, actual);
        assertCreditAccountDetailsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreditAccountDetailsAutoGeneratedPropertiesEquals(CreditAccountDetails expected, CreditAccountDetails actual) {
        assertThat(actual)
            .as("Verify CreditAccountDetails auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreditAccountDetailsUpdatableFieldsEquals(CreditAccountDetails expected, CreditAccountDetails actual) {
        assertThat(actual)
            .as("Verify CreditAccountDetails relevant properties")
            .satisfies(a ->
                assertThat(a.getCreditLimit())
                    .as("check creditLimit")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCreditLimit())
            )
            .satisfies(a -> assertThat(a.getStatementDay()).as("check statementDay").isEqualTo(expected.getStatementDay()))
            .satisfies(a -> assertThat(a.getPaymentDueDay()).as("check paymentDueDay").isEqualTo(expected.getPaymentDueDay()))
            .satisfies(a ->
                assertThat(a.getAnnualInterestRate())
                    .as("check annualInterestRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAnnualInterestRate())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreditAccountDetailsUpdatableRelationshipsEquals(CreditAccountDetails expected, CreditAccountDetails actual) {
        assertThat(actual)
            .as("Verify CreditAccountDetails relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()));
    }
}
