package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FileIngestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileIngestionAllPropertiesEquals(FileIngestion expected, FileIngestion actual) {
        assertFileIngestionAutoGeneratedPropertiesEquals(expected, actual);
        assertFileIngestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileIngestionAllUpdatablePropertiesEquals(FileIngestion expected, FileIngestion actual) {
        assertFileIngestionUpdatableFieldsEquals(expected, actual);
        assertFileIngestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileIngestionAutoGeneratedPropertiesEquals(FileIngestion expected, FileIngestion actual) {
        assertThat(actual)
            .as("Verify FileIngestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileIngestionUpdatableFieldsEquals(FileIngestion expected, FileIngestion actual) {
        assertThat(actual)
            .as("Verify FileIngestion relevant properties")
            .satisfies(a -> assertThat(a.getOriginalFilename()).as("check originalFilename").isEqualTo(expected.getOriginalFilename()))
            .satisfies(a -> assertThat(a.getFileType()).as("check fileType").isEqualTo(expected.getFileType()))
            .satisfies(a -> assertThat(a.getContentType()).as("check contentType").isEqualTo(expected.getContentType()))
            .satisfies(a -> assertThat(a.getFileSizeBytes()).as("check fileSizeBytes").isEqualTo(expected.getFileSizeBytes()))
            .satisfies(a -> assertThat(a.getChecksum()).as("check checksum").isEqualTo(expected.getChecksum()))
            .satisfies(a -> assertThat(a.getStorageKey()).as("check storageKey").isEqualTo(expected.getStorageKey()))
            .satisfies(a -> assertThat(a.getParserName()).as("check parserName").isEqualTo(expected.getParserName()))
            .satisfies(a -> assertThat(a.getParserVersion()).as("check parserVersion").isEqualTo(expected.getParserVersion()))
            .satisfies(a -> assertThat(a.getStatementStartDate()).as("check statementStartDate").isEqualTo(expected.getStatementStartDate())
            )
            .satisfies(a -> assertThat(a.getStatementEndDate()).as("check statementEndDate").isEqualTo(expected.getStatementEndDate()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileIngestionUpdatableRelationshipsEquals(FileIngestion expected, FileIngestion actual) {
        assertThat(actual)
            .as("Verify FileIngestion relationships")
            .satisfies(a ->
                assertThat(a.getTransactionIngestion()).as("check transactionIngestion").isEqualTo(expected.getTransactionIngestion())
            );
    }
}
