package com.fintrack.app.domain;

import static com.fintrack.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FinancialAccountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialAccountAllPropertiesEquals(FinancialAccount expected, FinancialAccount actual) {
        assertFinancialAccountAutoGeneratedPropertiesEquals(expected, actual);
        assertFinancialAccountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialAccountAllUpdatablePropertiesEquals(FinancialAccount expected, FinancialAccount actual) {
        assertFinancialAccountUpdatableFieldsEquals(expected, actual);
        assertFinancialAccountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialAccountAutoGeneratedPropertiesEquals(FinancialAccount expected, FinancialAccount actual) {
        assertThat(actual)
            .as("Verify FinancialAccount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialAccountUpdatableFieldsEquals(FinancialAccount expected, FinancialAccount actual) {
        assertThat(actual)
            .as("Verify FinancialAccount relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getInstitutionName()).as("check institutionName").isEqualTo(expected.getInstitutionName()))
            .satisfies(a -> assertThat(a.getAccountType()).as("check accountType").isEqualTo(expected.getAccountType()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a ->
                assertThat(a.getInitialBalance())
                    .as("check initialBalance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getInitialBalance())
            )
            .satisfies(a -> assertThat(a.getInitialBalanceDate()).as("check initialBalanceDate").isEqualTo(expected.getInitialBalanceDate())
            )
            .satisfies(a -> assertThat(a.getLastFourDigits()).as("check lastFourDigits").isEqualTo(expected.getLastFourDigits()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getColor()).as("check color").isEqualTo(expected.getColor()))
            .satisfies(a -> assertThat(a.getIcon()).as("check icon").isEqualTo(expected.getIcon()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getIncludeInNetWorth()).as("check includeInNetWorth").isEqualTo(expected.getIncludeInNetWorth()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialAccountUpdatableRelationshipsEquals(FinancialAccount expected, FinancialAccount actual) {
        assertThat(actual)
            .as("Verify FinancialAccount relationships")
            .satisfies(a -> assertThat(a.getBudgets()).as("check budgets").isEqualTo(expected.getBudgets()))
            .satisfies(a ->
                assertThat(a.getTransactionIngestions()).as("check transactionIngestions").isEqualTo(expected.getTransactionIngestions())
            )
            .satisfies(a -> assertThat(a.getApiAccessTokens()).as("check apiAccessTokens").isEqualTo(expected.getApiAccessTokens()));
    }
}
