package com.fintrack.app.domain;

import static com.fintrack.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FinancialTransactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialTransactionAllPropertiesEquals(FinancialTransaction expected, FinancialTransaction actual) {
        assertFinancialTransactionAutoGeneratedPropertiesEquals(expected, actual);
        assertFinancialTransactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialTransactionAllUpdatablePropertiesEquals(FinancialTransaction expected, FinancialTransaction actual) {
        assertFinancialTransactionUpdatableFieldsEquals(expected, actual);
        assertFinancialTransactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialTransactionAutoGeneratedPropertiesEquals(FinancialTransaction expected, FinancialTransaction actual) {
        assertThat(actual)
            .as("Verify FinancialTransaction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialTransactionUpdatableFieldsEquals(FinancialTransaction expected, FinancialTransaction actual) {
        assertThat(actual)
            .as("Verify FinancialTransaction relevant properties")
            .satisfies(a -> assertThat(a.getTransactionDate()).as("check transactionDate").isEqualTo(expected.getTransactionDate()))
            .satisfies(a -> assertThat(a.getPostingDate()).as("check postingDate").isEqualTo(expected.getPostingDate()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getFlow()).as("check flow").isEqualTo(expected.getFlow()))
            .satisfies(a -> assertThat(a.getOrigin()).as("check origin").isEqualTo(expected.getOrigin()))
            .satisfies(a -> assertThat(a.getExternalReference()).as("check externalReference").isEqualTo(expected.getExternalReference()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialTransactionUpdatableRelationshipsEquals(FinancialTransaction expected, FinancialTransaction actual) {
        assertThat(actual)
            .as("Verify FinancialTransaction relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a ->
                assertThat(a.getFinancialSubscription()).as("check financialSubscription").isEqualTo(expected.getFinancialSubscription())
            )
            .satisfies(a ->
                assertThat(a.getTransactionIngestion()).as("check transactionIngestion").isEqualTo(expected.getTransactionIngestion())
            )
            .satisfies(a -> assertThat(a.getTags()).as("check tags").isEqualTo(expected.getTags()));
    }
}
