package com.fintrack.app.domain;

import static com.fintrack.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FinancialSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialSubscriptionAllPropertiesEquals(FinancialSubscription expected, FinancialSubscription actual) {
        assertFinancialSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertFinancialSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialSubscriptionAllUpdatablePropertiesEquals(
        FinancialSubscription expected,
        FinancialSubscription actual
    ) {
        assertFinancialSubscriptionUpdatableFieldsEquals(expected, actual);
        assertFinancialSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialSubscriptionAutoGeneratedPropertiesEquals(
        FinancialSubscription expected,
        FinancialSubscription actual
    ) {
        assertThat(actual)
            .as("Verify FinancialSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialSubscriptionUpdatableFieldsEquals(FinancialSubscription expected, FinancialSubscription actual) {
        assertThat(actual)
            .as("Verify FinancialSubscription relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getExpectedAmount())
                    .as("check expectedAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExpectedAmount())
            )
            .satisfies(a ->
                assertThat(a.getAmountTolerancePercentage())
                    .as("check amountTolerancePercentage")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAmountTolerancePercentage())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getRecurrenceUnit()).as("check recurrenceUnit").isEqualTo(expected.getRecurrenceUnit()))
            .satisfies(a -> assertThat(a.getIntervalCount()).as("check intervalCount").isEqualTo(expected.getIntervalCount()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getNextExpectedDate()).as("check nextExpectedDate").isEqualTo(expected.getNextExpectedDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getAutomaticPayment()).as("check automaticPayment").isEqualTo(expected.getAutomaticPayment()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialSubscriptionUpdatableRelationshipsEquals(
        FinancialSubscription expected,
        FinancialSubscription actual
    ) {
        assertThat(actual)
            .as("Verify FinancialSubscription relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getTags()).as("check tags").isEqualTo(expected.getTags()));
    }
}
