package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IngestionRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngestionRecordAllPropertiesEquals(IngestionRecord expected, IngestionRecord actual) {
        assertIngestionRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertIngestionRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngestionRecordAllUpdatablePropertiesEquals(IngestionRecord expected, IngestionRecord actual) {
        assertIngestionRecordUpdatableFieldsEquals(expected, actual);
        assertIngestionRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngestionRecordAutoGeneratedPropertiesEquals(IngestionRecord expected, IngestionRecord actual) {
        assertThat(actual)
            .as("Verify IngestionRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngestionRecordUpdatableFieldsEquals(IngestionRecord expected, IngestionRecord actual) {
        assertThat(actual)
            .as("Verify IngestionRecord relevant properties")
            .satisfies(a -> assertThat(a.getRecordIndex()).as("check recordIndex").isEqualTo(expected.getRecordIndex()))
            .satisfies(a -> assertThat(a.getExternalRecordId()).as("check externalRecordId").isEqualTo(expected.getExternalRecordId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRawData()).as("check rawData").isEqualTo(expected.getRawData()))
            .satisfies(a -> assertThat(a.getErrorCode()).as("check errorCode").isEqualTo(expected.getErrorCode()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIngestionRecordUpdatableRelationshipsEquals(IngestionRecord expected, IngestionRecord actual) {
        assertThat(actual)
            .as("Verify IngestionRecord relationships")
            .satisfies(a ->
                assertThat(a.getFinancialTransaction()).as("check financialTransaction").isEqualTo(expected.getFinancialTransaction())
            )
            .satisfies(a ->
                assertThat(a.getTransactionIngestion()).as("check transactionIngestion").isEqualTo(expected.getTransactionIngestion())
            );
    }
}
