package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InternalTransferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalTransferAllPropertiesEquals(InternalTransfer expected, InternalTransfer actual) {
        assertInternalTransferAutoGeneratedPropertiesEquals(expected, actual);
        assertInternalTransferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalTransferAllUpdatablePropertiesEquals(InternalTransfer expected, InternalTransfer actual) {
        assertInternalTransferUpdatableFieldsEquals(expected, actual);
        assertInternalTransferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalTransferAutoGeneratedPropertiesEquals(InternalTransfer expected, InternalTransfer actual) {
        assertThat(actual)
            .as("Verify InternalTransfer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalTransferUpdatableFieldsEquals(InternalTransfer expected, InternalTransfer actual) {
        assertThat(actual)
            .as("Verify InternalTransfer relevant properties")
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalTransferUpdatableRelationshipsEquals(InternalTransfer expected, InternalTransfer actual) {
        // Transaction legs are immutable after create.
    }
}
