package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransactionRuleConditionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleConditionAllPropertiesEquals(
        TransactionRuleCondition expected,
        TransactionRuleCondition actual
    ) {
        assertTransactionRuleConditionAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionRuleConditionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleConditionAllUpdatablePropertiesEquals(
        TransactionRuleCondition expected,
        TransactionRuleCondition actual
    ) {
        assertTransactionRuleConditionUpdatableFieldsEquals(expected, actual);
        assertTransactionRuleConditionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleConditionAutoGeneratedPropertiesEquals(
        TransactionRuleCondition expected,
        TransactionRuleCondition actual
    ) {
        assertThat(actual)
            .as("Verify TransactionRuleCondition auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleConditionUpdatableFieldsEquals(
        TransactionRuleCondition expected,
        TransactionRuleCondition actual
    ) {
        assertThat(actual)
            .as("Verify TransactionRuleCondition relevant properties")
            .satisfies(a -> assertThat(a.getField()).as("check field").isEqualTo(expected.getField()))
            .satisfies(a -> assertThat(a.getOperator()).as("check operator").isEqualTo(expected.getOperator()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getSecondValue()).as("check secondValue").isEqualTo(expected.getSecondValue()))
            .satisfies(a -> assertThat(a.getCaseSensitive()).as("check caseSensitive").isEqualTo(expected.getCaseSensitive()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleConditionUpdatableRelationshipsEquals(
        TransactionRuleCondition expected,
        TransactionRuleCondition actual
    ) {
        assertThat(actual)
            .as("Verify TransactionRuleCondition relationships")
            .satisfies(a -> assertThat(a.getTransactionRule()).as("check transactionRule").isEqualTo(expected.getTransactionRule()));
    }
}
