package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransactionIngestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionIngestionAllPropertiesEquals(TransactionIngestion expected, TransactionIngestion actual) {
        assertTransactionIngestionAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionIngestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionIngestionAllUpdatablePropertiesEquals(TransactionIngestion expected, TransactionIngestion actual) {
        assertTransactionIngestionUpdatableFieldsEquals(expected, actual);
        assertTransactionIngestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionIngestionAutoGeneratedPropertiesEquals(TransactionIngestion expected, TransactionIngestion actual) {
        assertThat(actual)
            .as("Verify TransactionIngestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionIngestionUpdatableFieldsEquals(TransactionIngestion expected, TransactionIngestion actual) {
        assertThat(actual)
            .as("Verify TransactionIngestion relevant properties")
            .satisfies(a -> assertThat(a.getIngestionType()).as("check ingestionType").isEqualTo(expected.getIngestionType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getSourceLabel()).as("check sourceLabel").isEqualTo(expected.getSourceLabel()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getRecordsReceived()).as("check recordsReceived").isEqualTo(expected.getRecordsReceived()))
            .satisfies(a -> assertThat(a.getRecordsCreated()).as("check recordsCreated").isEqualTo(expected.getRecordsCreated()))
            .satisfies(a -> assertThat(a.getRecordsSkipped()).as("check recordsSkipped").isEqualTo(expected.getRecordsSkipped()))
            .satisfies(a -> assertThat(a.getRecordsRejected()).as("check recordsRejected").isEqualTo(expected.getRecordsRejected()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionIngestionUpdatableRelationshipsEquals(TransactionIngestion expected, TransactionIngestion actual) {
        assertThat(actual)
            .as("Verify TransactionIngestion relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()));
    }
}
