package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransactionRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleAllPropertiesEquals(TransactionRule expected, TransactionRule actual) {
        assertTransactionRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleAllUpdatablePropertiesEquals(TransactionRule expected, TransactionRule actual) {
        assertTransactionRuleUpdatableFieldsEquals(expected, actual);
        assertTransactionRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleAutoGeneratedPropertiesEquals(TransactionRule expected, TransactionRule actual) {
        assertThat(actual)
            .as("Verify TransactionRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleUpdatableFieldsEquals(TransactionRule expected, TransactionRule actual) {
        assertThat(actual)
            .as("Verify TransactionRule relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getConditionLogic()).as("check conditionLogic").isEqualTo(expected.getConditionLogic()))
            .satisfies(a ->
                assertThat(a.getResultingDescription()).as("check resultingDescription").isEqualTo(expected.getResultingDescription())
            )
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRuleUpdatableRelationshipsEquals(TransactionRule expected, TransactionRule actual) {
        assertThat(actual)
            .as("Verify TransactionRule relationships")
            .satisfies(a -> assertThat(a.getResultingCategory()).as("check resultingCategory").isEqualTo(expected.getResultingCategory()))
            .satisfies(a ->
                assertThat(a.getResultingFinancialSubscription())
                    .as("check resultingFinancialSubscription")
                    .isEqualTo(expected.getResultingFinancialSubscription())
            )
            .satisfies(a -> assertThat(a.getResultingTags()).as("check resultingTags").isEqualTo(expected.getResultingTags()));
    }
}
