package com.fintrack.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDashboardPreferenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDashboardPreferenceAllPropertiesEquals(UserDashboardPreference expected, UserDashboardPreference actual) {
        assertUserDashboardPreferenceAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDashboardPreferenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDashboardPreferenceAllUpdatablePropertiesEquals(
        UserDashboardPreference expected,
        UserDashboardPreference actual
    ) {
        assertUserDashboardPreferenceUpdatableFieldsEquals(expected, actual);
        assertUserDashboardPreferenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDashboardPreferenceAutoGeneratedPropertiesEquals(
        UserDashboardPreference expected,
        UserDashboardPreference actual
    ) {
        assertThat(actual)
            .as("Verify UserDashboardPreference auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDashboardPreferenceUpdatableFieldsEquals(
        UserDashboardPreference expected,
        UserDashboardPreference actual
    ) {
        assertThat(actual)
            .as("Verify UserDashboardPreference relevant properties")
            .satisfies(a -> assertThat(a.getConfiguration()).as("check configuration").isEqualTo(expected.getConfiguration()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDashboardPreferenceUpdatableRelationshipsEquals(
        UserDashboardPreference expected,
        UserDashboardPreference actual
    ) {
        // empty method
    }
}
