package com.fintrack.app.service.rules;

public enum RuleOutputSkipReason {
    CATEGORY_ALREADY_SUGGESTED_BY_HIGHER_PRIORITY_RULE,
    CATEGORY_CONFLICTS_WITH_EXPLICIT_VALUE,
    TAG_ALREADY_PRESENT,
    TAG_ALREADY_SUGGESTED,
    OUTPUT_INVALID_FOR_TRANSACTION,
}
