export enum IngestionStatus {
  PENDING = 'PENDING',

  READY = 'READY',

  PARTIALLY_READY = 'PARTIALLY_READY',

  PROCESSING = 'PROCESSING',

  COMPLETED = 'COMPLETED',

  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',

  FAILED = 'FAILED',
}
