export enum IngestionRecordStatus {
  VALID = 'VALID',

  DISABLED = 'DISABLED',

  IMPORTED = 'IMPORTED',

  SKIPPED_DUPLICATE = 'SKIPPED_DUPLICATE',

  REJECTED = 'REJECTED',

  FAILED = 'FAILED',
}
