export enum RuleOperator {
  EQUALS = 'EQUALS',

  NOT_EQUALS = 'NOT_EQUALS',

  CONTAINS = 'CONTAINS',

  NOT_CONTAINS = 'NOT_CONTAINS',

  STARTS_WITH = 'STARTS_WITH',

  ENDS_WITH = 'ENDS_WITH',

  REGEX = 'REGEX',

  GREATER_THAN = 'GREATER_THAN',

  GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL',

  LESS_THAN = 'LESS_THAN',

  LESS_THAN_OR_EQUAL = 'LESS_THAN_OR_EQUAL',

  BEFORE = 'BEFORE',

  AFTER = 'AFTER',

  BETWEEN = 'BETWEEN',

  IN = 'IN',

  NOT_IN = 'NOT_IN',
}
